(() => {
  'use strict';
  const K = { users:'zeus_users_v4', session:'zeus_session_v4', data:'zeus_data_v4', theme:'zeus_theme_v4', backend:'zeus_backend_v4' };
  const codes = {
    'ZCORP-PRO-7K4M-2026':'Pro','ZCORP-PRO-9Q2X-2026':'Pro','ZCORP-PRO-X8L5-2026':'Pro','ZCORP-PRO-M3T7-2026':'Pro','ZCORP-PRO-V6N1-2026':'Pro',
    'ZCORP-ULTRA-A9K2-2026':'Ultra','ZCORP-ULTRA-F4Q8-2026':'Ultra','ZCORP-ULTRA-H7M3-2026':'Ultra','ZCORP-ULTRA-R5X9-2026':'Ultra','ZCORP-ULTRA-Y2P6-2026':'Ultra'
  };
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const safe = (v, fallback) => { try { return JSON.parse(v) ?? fallback } catch { return fallback } };
  const getUsers = () => safe(localStorage.getItem(K.users), []);
  const setUsers = u => localStorage.setItem(K.users, JSON.stringify(u));
  const getSession = () => safe(localStorage.getItem(K.session), null);
  const setSession = s => localStorage.setItem(K.session, JSON.stringify(s));
  const uid = () => Math.random().toString(36).slice(2) + Date.now().toString(36);
  let state = { mode:'fast', view:'home', authMode:'login', data:null };

  function toast(msg){ const t=$('#toast'); t.textContent=msg; t.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>t.classList.remove('show'),2600); }
  function currentUser(){ const s=getSession(); return s ? getUsers().find(u=>u.id===s.id) : null; }
  function dataKey(id){ return K.data+'_'+id; }
  function loadData(){ const u=currentUser(); state.data = u ? safe(localStorage.getItem(dataKey(u.id)), {chats:[],messages:[],memories:[],files:[],activity:[]}) : null; }
  function saveData(){ const u=currentUser(); if(u&&state.data) localStorage.setItem(dataKey(u.id), JSON.stringify(state.data)); }
  function activity(text){ if(!state.data) return; state.data.activity.unshift({id:uid(),text,at:new Date().toISOString()}); state.data.activity=state.data.activity.slice(0,50); saveData(); }
  function escape(s){ return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
  function formatDate(d){ try{return new Date(d).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}catch{return ''} }

  function showAuth(mode){ state.authMode=mode; $('#nameField').classList.toggle('hidden',mode!=='register'); $('#authTitle').textContent=mode==='register'?'Create your ZEUS account':'Welcome back.'; $('#authSubtitle').textContent=mode==='register'?'Create a local ZCORP AI workspace in seconds.':'Sign in to enter your private AI workspace.'; $('#authSubmit').innerHTML=mode==='register'?'Create account <span>→</span>':'Sign in <span>→</span>'; $('#switchAuth').textContent=mode==='register'?'Already have an account? Sign in':'Create a new account'; $('#authPassword').autocomplete=mode==='register'?'new-password':'current-password'; }
  function enterApp(){ $('#authScreen').classList.add('hidden'); $('#appScreen').classList.remove('hidden'); loadData(); hydrate(); navigate(state.view||'home'); }
  function logout(){ localStorage.removeItem(K.session); state.data=null; $('#appScreen').classList.add('hidden'); $('#authScreen').classList.remove('hidden'); $('#authForm').reset(); showAuth('login'); toast('Signed out'); }

  $('#authForm').addEventListener('submit', e=>{ e.preventDefault(); const email=$('#authEmail').value.trim().toLowerCase(), pass=$('#authPassword').value; const name=$('#authName').value.trim()||email.split('@')[0]; if(!email||pass.length<4)return toast('Enter a valid email and a password of 4+ characters.'); const users=getUsers(); if(state.authMode==='register'){ if(users.some(u=>u.email===email)) return toast('An account with that email already exists.'); const u={id:uid(),email,name,plan:'Free',createdAt:new Date().toISOString()}; u.password=pass; users.push(u); setUsers(users); setSession({id:u.id}); localStorage.setItem(dataKey(u.id),JSON.stringify({chats:[],messages:[],memories:[],files:[],activity:[{id:uid(),text:'Account created',at:new Date().toISOString()}]})); toast('Account created — opening ZEUS…'); enterApp(); } else { const u=users.find(x=>x.email===email&&x.password===pass); if(!u)return toast('Incorrect email or password.'); setSession({id:u.id}); toast('Welcome back — opening ZEUS…'); enterApp(); } });
  $('#switchAuth').addEventListener('click',()=>showAuth(state.authMode==='login'?'register':'login'));
  $('#togglePassword').addEventListener('click',()=>{const i=$('#authPassword');i.type=i.type==='password'?'text':'password'});
  $('#logoutBtn').addEventListener('click',logout);

  function hydrate(){ const u=currentUser(); if(!u)return; $('#sideName').textContent=u.name; $('#sideEmail').textContent=u.email; $('#planPill').textContent=u.plan.toUpperCase(); $('#homePlan').textContent=u.plan.toUpperCase(); $('#homePlanText').textContent=u.plan==='Free'?'Starter access':`${u.plan} access unlocked`; $('#homeChats').textContent=state.data.chats.length; $('#homeMemory').textContent=state.data.memories.length; $('#homeFiles').textContent=state.data.files.length; $('#adminAccounts').textContent=getUsers().length; $('#adminPlan').textContent=u.plan.toUpperCase(); $('#adminChats').textContent=state.data.chats.length; $('#settingsName').value=u.name; $('#backendUrl').value=localStorage.getItem(K.backend)||''; renderMessages(); renderFiles(); renderMemory(); renderHistory(); }
  function navigate(view){ state.view=view; $$('.view').forEach(v=>v.classList.remove('active-view')); const target=$('#view-'+view); if(target)target.classList.add('active-view'); $$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view)); $('#crumbView').textContent=view.charAt(0).toUpperCase()+view.slice(1); $('#sidebar').classList.remove('open'); window.scrollTo({top:0,behavior:'smooth'}); if(view==='chat')$('#chatInput').focus(); }
  document.addEventListener('click',e=>{const v=e.target.closest('[data-view]'); if(v)navigate(v.dataset.view)});
  $('#openSidebar').addEventListener('click',()=>$('#sidebar').classList.add('open')); $('#closeSidebar').addEventListener('click',()=>$('#sidebar').classList.remove('open')); $('#newChat').addEventListener('click',()=>{state.data.messages=[];saveData();renderMessages();navigate('chat');toast('New chat started')});

  function aiReply(text, mode){ const t=text.toLowerCase(); if(mode==='research') return `Research mode is ready.\n\nFor “${text}”, ZEUS would structure the work into:\n1. Define the exact research question.\n2. Gather and compare credible sources.\n3. Extract evidence, dates and key numbers.\n4. Highlight disagreements and risks.\n5. Deliver a concise conclusion with next actions.\n\nConnect a secure Gemini backend in Settings to replace this local response with live model output.`; if(mode==='agent') return `Agent plan for: ${text}\n\nPHASE 1 — Clarify\n• Define the desired outcome and constraints.\n\nPHASE 2 — Execute\n• Break the goal into small, testable tasks.\n• Complete the highest-impact task first.\n\nPHASE 3 — Verify\n• Check quality, edge cases and missing requirements.\n\nPHASE 4 — Deliver\n• Package the result and list the next recommended action.\n\nFor autonomous execution with live AI, add your secure Render backend URL in Settings.`; if(t.includes('hello')||t.includes('hi ')) return `Hello ${currentUser()?.name||'there'} 👋\n\nI’m ZEUS, your ZCORP AI workspace. Tell me what you want to build, research, write or solve.`; if(t.includes('code')) return `Absolutely. I can help you design the solution, explain the architecture, find bugs and produce production-ready code.\n\nFor live Gemini generation, connect your Render backend in Settings.`; return `I’m ready. You asked:\n\n“${text}”\n\nHere’s a useful starting point: clarify the outcome, identify constraints, split the task into smaller actions, then verify each result.\n\n⚡ Mode: ${mode.toUpperCase()}\n\nConnect your secure Gemini backend in Settings when you want live model responses.`; }
  function renderMessages(){ const box=$('#chatMessages'); if(!state.data){box.innerHTML='';return} if(!state.data.messages.length){box.innerHTML='<div class="message ai"><span class="who">ZEUS</span>Welcome to your workspace. Ask me anything, or choose a mode above.</div>';return} box.innerHTML=state.data.messages.map(m=>`<div class="message ${m.role}"><span class="who">${m.role==='user'?'YOU':'ZEUS'}</span>${escape(m.text)}</div>`).join(''); box.scrollTop=box.scrollHeight; }
  $('#chatForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return; state.data.messages.push({id:uid(),role:'user',text,at:new Date().toISOString(),mode:state.mode}); input.value='';renderMessages(); activity('Sent a message'); const backend=(localStorage.getItem(K.backend)||'').replace(/\/$/,''); let reply=''; if(backend){ try{const r=await fetch(backend+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,mode:state.mode})}); if(r.ok){const j=await r.json();reply=j.text||j.response||j.message||'';} }catch{} } if(!reply)reply=aiReply(text,state.mode); state.data.messages.push({id:uid(),role:'ai',text:reply,at:new Date().toISOString(),mode:state.mode}); state.data.chats.push({id:uid(),title:text.slice(0,60),at:new Date().toISOString()});saveData();renderMessages();hydrate(); });
  $('#clearChat').addEventListener('click',()=>{if(confirm('Clear this conversation?')){state.data.messages=[];saveData();renderMessages();toast('Conversation cleared')}});
  $$('.mode').forEach(b=>b.addEventListener('click',()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;$('#chatStatus').textContent=`${b.textContent.trim()} mode selected.`}));

  async function runTool(kind,input){ if(!input.trim())return toast('Enter a prompt first.'); const u=currentUser(); if((kind==='research'||kind==='agent'||kind==='code')&&!['Pro','Ultra'].includes(u.plan))return navigate('upgrade'),toast('This workspace requires Pro or Ultra.'); const backend=(localStorage.getItem(K.backend)||'').replace(/\/$/,''); if(backend){ try{const r=await fetch(backend+'/api/'+kind,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:input})});if(r.ok){const j=await r.json();return j.text||j.result||j.code||JSON.stringify(j,null,2)}}catch{} } if(kind==='research')return aiReply(input,'research'); if(kind==='agent')return aiReply(input,'agent'); return `// ZEUS Code Studio\n// Prompt: ${input}\n\nfunction solution() {\n  // Connect the secure Gemini backend to generate production code.\n  return "Ready to build";\n}`; }
  $('#runResearch').addEventListener('click',async()=>{$('#researchResult').classList.remove('empty');$('#researchResult').textContent='ZEUS is preparing your research brief…';$('#researchResult').textContent=await runTool('research',$('#researchInput').value)});
  $('#saveResearch').addEventListener('click',()=>{const v=$('#researchResult').textContent.trim();if(v&&v!=='Your research brief will appear here.'){state.data.activity.unshift({id:uid(),text:'Saved a research brief',at:new Date().toISOString()});saveData();toast('Research brief saved')}});
  $('#runAgent').addEventListener('click',async()=>{$('#agentResult').classList.remove('empty');$('#agentResult').textContent='ZEUS is building your plan…';$('#agentResult').textContent=await runTool('agent',$('#agentInput').value)});
  $('#generateCode').addEventListener('click',async()=>{$('#codeResult').textContent=await runTool('code',$('#codeInput').value)});
  $('#explainCode').addEventListener('click',async()=>{$('#codeResult').textContent=await runTool('agent','Explain the implementation approach for: '+$('#codeInput').value)});

  function addFiles(list){[...list].forEach(f=>{state.data.files.unshift({id:uid(),name:f.name,size:f.size,type:f.type,at:new Date().toISOString()})});saveData();renderFiles();hydrate();toast(`${list.length} file(s) added to local workspace`)}
  $('#fileInput').addEventListener('change',e=>{if(e.target.files.length)addFiles(e.target.files);e.target.value=''}); $('#chatFile').addEventListener('change',e=>{if(e.target.files.length)addFiles(e.target.files);e.target.value=''});
  function renderFiles(){const box=$('#fileList');box.innerHTML=state.data.files.length?state.data.files.map(f=>`<div class="list-row"><div><strong>▣ ${escape(f.name)}</strong><small>${Math.max(1,f.size/1024).toFixed(1)} KB • ${formatDate(f.at)}</small></div><button class="danger-btn" data-del-file="${f.id}">Remove</button></div>`).join(''):'<div class="list-row"><div><strong>No files yet</strong><small>Upload documents, images or code files from this device.</small></div></div>';}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-del-file]');if(b){state.data.files=state.data.files.filter(f=>f.id!==b.dataset.delFile);saveData();renderFiles();hydrate();}});

  $('#memoryForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#memoryInput').value.trim();if(!v)return;state.data.memories.unshift({id:uid(),text:v,at:new Date().toISOString()});$('#memoryInput').value='';saveData();renderMemory();hydrate();toast('Memory saved')});
  function renderMemory(){const box=$('#memoryList');box.innerHTML=state.data.memories.length?state.data.memories.map(m=>`<div class="list-row"><div><strong>${escape(m.text)}</strong><small>${formatDate(m.at)}</small></div><button class="danger-btn" data-del-memory="${m.id}">Remove</button></div>`).join(''):'<div class="list-row"><div><strong>No memories saved</strong><small>Add preferences, goals or facts you want to keep locally.</small></div></div>';}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-del-memory]');if(b){state.data.memories=state.data.memories.filter(m=>m.id!==b.dataset.delMemory);saveData();renderMemory();hydrate();}});
  function renderHistory(){const box=$('#historyList');const items=[...state.data.activity,...state.data.chats.map(c=>({id:c.id,text:'Chat: '+c.title,at:c.at}))].sort((a,b)=>new Date(b.at)-new Date(a.at));box.innerHTML=items.length?items.slice(0,50).map(x=>`<div class="list-row"><div><strong>${escape(x.text)}</strong><small>${formatDate(x.at)}</small></div></div>`).join(''):'<div class="list-row"><div><strong>No activity yet</strong><small>Your activity will appear here.</small></div></div>';}
  $('#exportData').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({user:currentUser(),data:state.data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='zeus-workspace.json';a.click();URL.revokeObjectURL(a.href);toast('Workspace exported')});

  $$('.plan-btn').forEach(b=>b.addEventListener('click',()=>{const plan=b.dataset.plan;if(plan==='Free'){switchPlan('Free');return} notifyBank(plan)}));
  function switchPlan(plan){const users=getUsers(),u=currentUser(),i=users.findIndex(x=>x.id===u.id);if(i<0)return;users[i].plan=plan;setUsers(users);activity(`Plan changed to ${plan}`);hydrate();toast(`ZEUS ${plan} access unlocked`);}
  $('#redeemForm').addEventListener('submit',e=>{e.preventDefault();const code=$('#redeemInput').value.trim().toUpperCase();if(!codes[code])return toast('Invalid or unavailable premium code.');const plan=codes[code];const used=safe(localStorage.getItem('zeus_used_codes'),[]);if(used.includes(code))return toast('That code has already been redeemed on this browser.');used.push(code);localStorage.setItem('zeus_used_codes',JSON.stringify(used));switchPlan(plan);$('#redeemInput').value='';});
  function notifyBank(plan){const amounts={Plus:'5000',Pro:'10000',Ultra:'20000'};const u=currentUser();const text=`Hello ZCORP ORG, I want to upgrade my ZEUS account.\n\nName: ${u.name}\nEmail: ${u.email}\nPlan: ${plan}\nAmount: ₦${amounts[plan]}\n\nI have made the bank/Opay transfer and would like my plan activated.`;window.open('https://wa.me/2349066760078?text='+encodeURIComponent(text),'_blank');toast('Opening WhatsApp payment notification…')}
  $('#bankNotify').addEventListener('click',()=>notifyBank('Pro'));

  function setTheme(){const t=localStorage.getItem(K.theme)||'dark';document.body.classList.toggle('light',t==='light');}
  function toggleTheme(){const next=document.body.classList.contains('light')?'dark':'light';localStorage.setItem(K.theme,next);setTheme();toast(`${next==='dark'?'Dark':'Light'} mode enabled`)}
  $('#themeBtn').addEventListener('click',toggleTheme);$('#settingsTheme').addEventListener('click',toggleTheme);
  $('#backendUrl').addEventListener('change',e=>{localStorage.setItem(K.backend,e.target.value.trim().replace(/\/$/,''));toast('Backend URL saved')});
  $('#settingsName').addEventListener('change',e=>{const users=getUsers(),u=currentUser(),i=users.findIndex(x=>x.id===u.id);if(i>=0){users[i].name=e.target.value.trim()||u.name;setUsers(users);hydrate();toast('Name updated')}});
  $('#resetData').addEventListener('click',()=>{if(!confirm('Delete this browser\'s ZEUS account, chats, memory and settings?'))return;const u=currentUser();if(u){setUsers(getUsers().filter(x=>x.id!==u.id));localStorage.removeItem(dataKey(u.id));}localStorage.removeItem(K.session);localStorage.removeItem(K.backend);location.reload();});
  $('#voiceBtn').addEventListener('click',()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('Voice input is not supported by this browser.');const r=new SR();r.lang='en-NG';r.interimResults=false;r.onresult=e=>{$('#chatInput').value=e.results[0][0].transcript;toast('Voice captured')};r.onerror=()=>toast('Voice input failed');r.start();});
  setTheme(); showAuth('login'); if(getSession()&&currentUser())enterApp();
})();
