const KEY='zcorp_zeus_v4';
const API_URL=(localStorage.getItem('zeus_api_url')||'https://zcorp-ai-backend.onrender.com').replace(/\/$/,'');
const PLAN_ORDER={FREE:0,PLUS:1,PRO:2,ULTRA:3};
const FEATURES=['Real Gemini AI','Research + web search','Agent planning','Code Studio','Local memory','File workspace','Voice input','Conversation history','Prompt library','Export conversations','Theme controls','Usage dashboard','Premium code redemption','Manual bank transfer','Payment submission','WhatsApp payment notification','Mobile-first UI'];
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{users:[],session:null,theme:'dark'};
let state=JSON.parse(localStorage.getItem(KEY+'_state')||'null')||{view:'home',mode:'fast',chat:[],files:[],memory:[],history:[],code:'// 👑 ZEUS Code Studio\n// Ask ZEUS to write, explain, refactor or review code.\n',research:'',agentTasks:[],promptLibrary:['Build a 30-day marketing plan for my business.','Explain this concept simply with examples.','Review this code for bugs and security issues.','Compare these options and recommend the best one.']};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(db))} function saveState(){localStorage.setItem(KEY+'_state',JSON.stringify(state))}
function user(){return db.users.find(x=>x.email===db.session)} function plan(){return user()?.plan||'FREE'}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2800)}
function escape(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function gate(required){if(PLAN_ORDER[plan()]<PLAN_ORDER[required]){toast(`🔒 ${required} required. Use a premium code or payment.`);state.view='upgrade';saveState();render();return false}return true}
function shell(title,body){$('#pageTitle').textContent=title;$('#content').innerHTML=body;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#sidePlan').textContent=plan();$('#sideUser').textContent=user()?.name||'Guest';$('#sideEmail').textContent=user()?.email||'Local account';$('#avatar').textContent=(user()?.name||'Z').slice(0,1).toUpperCase();}
function home(){const u=user();shell('Home',`<div class="hero"><span class="badge">ZCORP ORG • 👑 ZEUS AI</span><h1>Welcome, <span>${escape(u.name)}</span>.</h1><p class="muted">Your private AI command center for chat, research, coding, files, memory and intelligent workflows.</p><div class="actions"><button class="btn primary" data-view="chat">✦ Start chatting</button><button class="btn" data-view="research">⌕ Research</button><button class="btn" data-view="agent">◈ Agent</button><button class="btn" data-view="upgrade">♛ Premium</button></div></div><div class="section grid grid-4"><div class="card stat"><span>✦</span><b>${state.chat.filter(x=>x.role==='user').length}</b><small>Prompts</small></div><div class="card stat"><span>▣</span><b>${state.files.length}</b><small>Files</small></div><div class="card stat"><span>◉</span><b>${state.memory.length}</b><small>Memories</small></div><div class="card stat"><span>♛</span><b>${plan()}</b><small>Plan</small></div></div><div class="section"><div class="view-head"><div><h2>ZEUS capabilities</h2><p>Everything is interactive and saved locally where appropriate.</p></div></div><div class="grid grid-4">${FEATURES.map((x,i)=>`<div class="card feature"><div class="icon">${['✦','⌕','◈','⌘','◉','▣','◌','◷','✎','↥','◐','▤','♛','₦','✓','⚡'][i]}</div><h3>${x}</h3><p>${i<2?'Connected through the secure Render backend when configured.':'Available directly in your ZEUS workspace.'}</p></div>`).join('')}</div></div><div class="section grid grid-3"><div class="card"><h3>⚡ Quick actions</h3><div class="actions"><button class="btn" data-action="quick" data-q="Create a professional business plan for ZCORP ORG.">Business plan</button><button class="btn" data-action="quick" data-q="Give me 10 startup ideas I can launch with low capital.">Ideas</button><button class="btn" data-action="quick" data-q="Write a premium landing page headline and copy.">Landing page</button></div></div><div class="card"><h3>⌨ Shortcuts</h3><p class="muted">⌘/Ctrl + Enter sends a message. Use the sidebar to switch workspaces.</p></div><div class="card"><h3>🔐 Privacy</h3><p class="muted">Local accounts and workspace data stay in this browser. Secrets belong only on the Render backend.</p></div></div><p class="footer-note">ZCORP ORG • BUILD. CREATE. SELL. INNOVATE.</p>`)}
function chat(){if(!state.chat.length)state.chat=[{role:'ai',text:'Welcome to ZEUS 👑. I’m connected to the ZCORP AI workspace. Ask me anything.'}];shell('Chat',`<div class="chat-wrap"><div class="view-head"><div><h2>AI Chat</h2><p>Real Gemini responses through your secure Render backend.</p></div><div class="actions"><button class="btn" data-action="export">↥ Export</button><button class="btn" data-action="clear-chat">Clear</button></div></div><div class="card" style="margin-bottom:12px"><div class="chips">${['fast','think','research','agent'].map(m=>`<button class="chip ${state.mode===m?'active':''}" data-mode="${m}">${m==='fast'?'⚡ Fast':m==='think'?'🧠 Think':m==='research'?'⌕ Research':'◈ Agent'}</button>`).join('')}<button class="chip" data-action="voice">🎙 Voice</button><button class="chip" data-action="attach">＋ File</button></div></div><div class="messages" id="messages">${state.chat.map(m=>`<div class="msg ${m.role==='user'?'user':'ai'}"><div class="bubble">${escape(m.text)}</div></div>`).join('')}</div><div class="composer"><textarea id="prompt" placeholder="Message ZEUS…"></textarea><div class="compose-row"><div class="chips"><button class="chip" data-action="memory-add">◉ Save prompt to memory</button><button class="chip" data-action="library">✎ Prompt library</button></div><button class="send" data-action="send">Send ↗</button></div></div></div>`);$('#messages').scrollTop=$('#messages').scrollHeight}
async function callAI(prompt,mode=state.mode,context=''){const r=await fetch(API_URL+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,mode,context})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'AI request failed');return d.text}
async function sendPrompt(p){if(!p)return;state.chat.push({role:'user',text:p});state.history.unshift({q:p,time:new Date().toLocaleString(),mode:state.mode});saveState();chat();const messages=$('#messages');state.chat.push({role:'ai',text:'ZEUS is thinking…'});chat();try{const context=state.memory.slice(0,20).join('\n');const text=await callAI(p,state.mode,context);state.chat[state.chat.length-1]={role:'ai',text};saveState();chat()}catch(e){state.chat[state.chat.length-1]={role:'ai',text:'⚠️ '+e.message};saveState();chat()}}
function research(){if(!gate('PRO'))return;shell('Research',`<div class="view-head"><div><h2>Deep Research</h2><p>Use Gemini with web search for current research when your backend is configured.</p></div></div><div class="card"><textarea class="codebox" id="researchInput" style="min-height:180px" placeholder="What should ZEUS research?">${escape(state.research)}</textarea><div class="actions"><button class="btn primary" data-action="run-research">⌕ Research now</button><button class="btn" data-action="research-to-chat">Send to chat</button></div></div><div class="section" id="researchResult"></div>`)}
async function runResearch(){const q=$('#researchInput').value.trim();if(!q)return toast('Enter a research topic.');state.research=q;saveState();$('#researchResult').innerHTML='<div class="card"><p class="muted">ZEUS is researching…</p></div>';try{const text=await callAI(q,'research',state.memory.join('\n'));state.researchResult=text;$('#researchResult').innerHTML=`<div class="card"><span class="badge">RESEARCH RESULT</span><h3>ZEUS research brief</h3><div class="result-text">${escape(text)}</div></div>`;saveState()}catch(e){$('#researchResult').innerHTML=`<div class="card"><p class="danger">${escape(e.message)}</p></div>`}}
function agent(){if(!gate('PRO'))return;shell('Agent',`<div class="view-head"><div><h2>Agent Command Center</h2><p>Turn a goal into an actionable plan. External actions remain under your control.</p></div></div><div class="card"><textarea class="codebox" id="agentInput" style="min-height:150px" placeholder="Example: Launch a digital product in 14 days."></textarea><div class="actions"><button class="btn primary" data-action="run-agent">◈ Plan with ZEUS</button></div></div><div class="section grid grid-2">${state.agentTasks.map((t,i)=>`<div class="card"><span class="badge">STEP ${i+1}</span><h3>${escape(t)}</h3><button class="btn" data-action="agent-chat" data-q="Execute step ${i+1}: ${encodeURIComponent(t)}">Ask ZEUS</button></div>`).join('')}</div>`)}
async function runAgent(){const q=$('#agentInput').value.trim();if(!q)return toast('Give the agent a goal.');state.agentTasks=['Analyzing objective…'];agent();try{const text=await callAI('Create a concise execution plan for this goal. Return 5-8 numbered steps with concrete deliverables and risks:\n'+q,'agent',state.memory.join('\n'));state.agentTasks=text.split(/\n+/).filter(x=>x.trim()).slice(0,10);saveState();agent()}catch(e){state.agentTasks=['Backend error: '+e.message];saveState();agent()}}
function code(){if(!gate('PRO'))return;shell('Code Studio',`<div class="view-head"><div><h2>Code Studio</h2><p>Generate, explain, refactor and review code with Gemini.</p></div><div class="actions"><button class="btn" data-action="copy-code">Copy</button><button class="btn primary" data-action="save-code">Save</button><button class="btn" data-action="ai-code">Ask ZEUS</button></div></div><textarea class="codebox" id="codeEditor">${escape(state.code)}</textarea><div class="section grid grid-3"><div class="card tool-card"><div class="big">⌘</div><h3>Explain</h3><p>Explain the current code.</p><button class="btn" data-action="code-task" data-task="Explain this code line by line and point out important concepts.">Run</button></div><div class="card tool-card"><div class="big">⚡</div><h3>Refactor</h3><p>Improve quality and structure.</p><button class="btn" data-action="code-task" data-task="Refactor this code for readability, maintainability and security.">Run</button></div><div class="card tool-card"><div class="big">✓</div><h3>Review</h3><p>Find bugs and security issues.</p><button class="btn" data-action="code-task" data-task="Review this code for bugs, security risks and edge cases.">Run</button></div></div><div class="section card" id="codeResult"><p class="muted">AI code results appear here.</p></div>`)}
async function codeTask(task){const c=$('#codeEditor').value;$('#codeResult').innerHTML='<p class="muted">ZEUS is reviewing your code…</p>';try{const text=await callAI(task+'\n\nCODE:\n'+c,'think');$('#codeResult').innerHTML=`<div class="result-text">${escape(text)}</div>`}catch(e){$('#codeResult').innerHTML=`<p class="danger">${escape(e.message)}</p>`}}
function files(){shell('Files',`<div class="view-head"><div><h2>File Workspace</h2><p>Files and metadata are kept locally. Text files can be sent to ZEUS for analysis.</p></div></div><div class="drop"><input id="dropInput" type="file" multiple><div style="font-size:35px">▣</div><h3>Choose files</h3><p class="muted">Upload documents, images, code and more to this browser workspace.</p><button class="btn primary" data-action="choose-files">Choose files</button></div><div class="section card">${state.files.length?state.files.map((f,i)=>`<div class="file-row"><div>📄 <b>${escape(f.name)}</b><small class="muted"> • ${f.size}</small></div><div class="actions"><button class="btn" data-action="analyze-file" data-index="${i}">Analyze</button><button class="btn" data-action="remove-file" data-index="${i}">Remove</button></div></div>`).join(''):'<p class="muted">No files yet.</p>'}</div>`)}
function memory(){shell('Memory',`<div class="view-head"><div><h2>ZEUS Memory</h2><p>Persistent browser-local memories for this account.</p></div></div><div class="card"><div class="redeem"><input id="memoryInput" placeholder="Example: I prefer concise answers."><button class="btn primary" data-action="save-memory">Save</button></div></div><div class="section card">${state.memory.length?state.memory.map((m,i)=>`<div class="memory-row"><span>◉ ${escape(m)}</span><button class="btn" data-action="remove-memory" data-index="${i}">Delete</button></div>`).join(''):'<p class="muted">No memories saved.</p>'}</div>`)}
function history(){shell('History',`<div class="view-head"><div><h2>Conversation History</h2><p>Recent prompts are stored in local storage.</p></div><button class="btn" data-action="clear-history">Clear</button></div><div class="card">${state.history.length?state.history.map(h=>`<div class="history-row"><div><b>${escape(h.q)}</b><small class="muted">${escape(h.time)} • ${escape(h.mode)}</small></div><button class="btn" data-action="reuse" data-q="${encodeURIComponent(h.q)}">Reuse</button></div>`).join(''):'<p class="muted">No history yet.</p>'}</div>`)}
function upgrade(){shell('Upgrade',`<div class="view-head"><div><h2>Plans, Bank Payment & Premium Codes</h2><p>Choose a plan, transfer to the ZCORP account, then submit your payment details for approval.</p></div></div><div class="notice"><b>🏦 ZCORP BANK PAYMENT</b><br>Provider: <b>Opay</b><br>Account number: <b>9066760078</b><br>Account name: <b>CHRISTANA Godwin okon</b><br><span class="muted">After transfer, tap “I’ve Paid” and send your receipt/reference through WhatsApp.</span></div><div class="section grid grid-4">${[['FREE','₦0',['Basic Gemini','Memory','Files']],['PLUS','₦5,000',['Higher limits','More workspace','Priority UI']],['PRO','₦12,000',['Research','Agent','Code Studio','Advanced tools']],['ULTRA','₦25,000',['Everything in Pro','Ultra controls','Premium experience','Highest limits']]].map(p=>`<div class="card plan ${p[0]==='PRO'?'featured':''}"><span class="badge">${p[0]}</span><h3>${p[0]}</h3><div class="price">${p[1]} <small>/ month</small></div><ul>${p[2].map(x=>`<li>${x}</li>`).join('')}</ul>${p[0]==='FREE'?`<button class="btn" data-plan="FREE">${plan()==='FREE'?'Current plan':'Use Free'}</button>`:`<button class="btn primary" data-action="bank-pay" data-plan-name="${p[0]}" data-amount="${p[1]}">${plan()===p[0]?'Current plan':'🏦 Pay by Bank'}</button>`}</div>`).join('')}</div><div class="section card"><span class="badge">REDEEM PREMIUM CODE</span><h3>Unlock Pro or Ultra instantly</h3><p class="muted">Enter a valid ZCORP promotional code. Codes are stored as redeemed in this browser.</p><div class="redeem"><input id="premiumCode" autocapitalize="characters" placeholder="ZCORP-PRO-XXXX-2026"><button class="btn primary" data-action="redeem">Redeem Code</button></div></div><div class="section card"><span class="badge">PAYMENT SUBMISSION</span><h3>Already transferred?</h3><p class="muted">Submit the transfer details. ZEUS will prepare a WhatsApp message to ZCORP support with your payment information.</p><div class="form-grid"><select id="paidPlan"><option value="PLUS">PLUS — ₦5,000</option><option value="PRO">PRO — ₦12,000</option><option value="ULTRA">ULTRA — ₦25,000</option></select><input id="payerName" placeholder="Name used for the transfer"><input id="paymentRef" placeholder="Bank/Opay transaction reference"><input id="paidAmount" placeholder="Amount transferred, e.g. 12000" inputmode="numeric"></div><div class="actions"><button class="btn primary" data-action="bank-submit">✓ I've Paid — Notify ZCORP</button><button class="btn" data-action="copy-bank">Copy bank details</button></div></div><div class="section card"><h3>📱 Payment support</h3><p class="muted">WhatsApp: <b>09066760078</b><br>Email: <b>zcorporg40@gmail.com</b></p></div>`)}
function copyBank(){const text='ZCORP AI PAYMENT\nProvider: Opay\nAccount number: 9066760078\nAccount name: CHRISTANA Godwin okon';navigator.clipboard?.writeText(text);toast('🏦 Bank details copied.')} 
function submitBankPayment(){const u=user();const pl=$('#paidPlan').value;const name=$('#payerName').value.trim()||u?.name||'';const ref=$('#paymentRef').value.trim();const amount=$('#paidAmount').value.trim();if(!name||!ref||!amount)return toast('Enter your name, transaction reference and amount.');const msg=`Hello ZCORP ORG 👑%0A%0AI have made a bank/Opay payment for ZCORP AI.%0A%0AName: ${encodeURIComponent(name)}%0AEmail: ${encodeURIComponent(u?.email||'')}%0APlan: ${encodeURIComponent(pl)}%0AAmount: ₦${encodeURIComponent(amount)}%0ATransaction reference: ${encodeURIComponent(ref)}%0A%0APlease verify and activate my ${encodeURIComponent(pl)} plan.`;state.paymentSubmission={plan:pl,name,amount,ref,time:new Date().toISOString(),status:'submitted'};saveState();window.open('https://wa.me/2349066760078?text='+msg,'_blank');toast('📱 WhatsApp payment notification prepared.');}
async function redeem(){const c=$('#premiumCode').value.trim().toUpperCase();if(!c)return toast('Enter a premium code.');try{const r=await fetch(API_URL+'/api/redeem',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:c,email:user().email})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Invalid code');user().plan=d.plan;user().redeemedCodes=[...(user().redeemedCodes||[]),c];save();toast(`👑 ${d.plan} activated.`);render()}catch(e){toast('❌ '+e.message)}}
function pay(planName){if(planName==='FREE'){user().plan='FREE';save();toast('Switched to Free.');render();return}$('#paidPlan').value=planName;toast('Transfer to the ZCORP account, then submit your payment.')}
function voice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('Voice input is not supported on this browser.');const r=new R();r.lang='en-US';r.onresult=e=>{const p=$('#prompt');if(p)p.value=e.results[0][0].transcript};r.start();toast('🎙 Listening…')}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function addFiles(fs){const arr=[...fs];arr.forEach(f=>state.files.push({name:f.name,size:(f.size/1024).toFixed(1)+' KB',type:f.type}));saveState();files();toast(`${arr.length} file(s) added.`)}
let authMode='login';
$('#authForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#authName').value.trim(),email=$('#authEmail').value.trim().toLowerCase(),pw=$('#authPassword').value;if(!email||!pw||(authMode==='register'&&!name))return toast('Complete all fields.');if(authMode==='register'){if(db.users.some(x=>x.email===email))return toast('Account already exists.');db.users.push({name,email,pw,plan:'FREE',redeemedCodes:[]});db.session=email;save();toast('👑 Account created locally.');render()}else{const u=db.users.find(x=>x.email===email&&x.pw===pw);if(!u)return toast('Invalid email or password.');db.session=email;save();toast('Welcome back.');render()}});
$('#authToggle').onclick=()=>{authMode=authMode==='login'?'register':'login';$('#authTitle').textContent=authMode==='login'?'Welcome back.':'Create your ZEUS account.';$('#authSub').textContent=authMode==='login'?'Sign in to your private AI workspace.':'Create a local account for this browser.';$('#authName').classList.toggle('hidden',authMode==='login');$('#authSubmit').textContent=authMode==='login'?'Sign in':'Create account';$('#authToggle').textContent=authMode==='login'?'Create a new account':'Already have an account? Sign in'};
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;state.view=b.dataset.view;$('.sidebar').classList.remove('open');saveState();render()});
document.addEventListener('click',async e=>{const v=e.target.closest('[data-view]');if(v&&v.closest('#content')){state.view=v.dataset.view;saveState();render();return}const a=e.target.closest('[data-action]');if(!a)return;const act=a.dataset.action;try{
if(act==='new-chat'){state.chat=[];state.view='chat';saveState();render()}
else if(act==='logout'){db.session=null;save();render()}
else if(act==='theme'){db.theme=db.theme==='light'?'dark':'light';save();render()}
else if(act==='clear-chat'){state.chat=[];saveState();render()}
else if(act==='send'){const p=$('#prompt')?.value.trim();if(p){$('#prompt').value='';await sendPrompt(p)}}
else if(act==='export'){download('zeus-chat.txt',state.chat.map(m=>`${m.role.toUpperCase()}: ${m.text}`).join('\n\n'),'text/plain')}
else if(act==='voice')voice(); else if(act==='attach')$('#fileInput').click(); else if(act==='choose-files')$('#dropInput').click();
else if(act==='run-research')await runResearch(); else if(act==='research-to-chat'){state.view='chat';state.chat.push({role:'user',text:state.research||'Research this topic.'});saveState();render()}
else if(act==='run-agent')await runAgent(); else if(act==='agent-chat'){state.view='chat';saveState();render();await sendPrompt(decodeURIComponent(a.dataset.q))}
else if(act==='copy-code'){navigator.clipboard?.writeText($('#codeEditor').value);toast('Code copied.')} else if(act==='save-code'){state.code=$('#codeEditor').value;saveState();toast('Code saved locally.')} else if(act==='code-task')await codeTask(a.dataset.task); else if(act==='ai-code')await codeTask('Improve or analyze this code and return actionable recommendations.');
else if(act==='save-memory'){const x=$('#memoryInput').value.trim();if(x){state.memory.unshift(x);saveState();memory();toast('Memory saved.')}} else if(act==='memory-add'){const p=$('#prompt')?.value.trim();if(p){state.memory.unshift(p);saveState();toast('Prompt saved to memory.')}} else if(act==='remove-memory'){state.memory.splice(+a.dataset.index,1);saveState();memory()}
else if(act==='clear-history'){state.history=[];saveState();history()} else if(act==='reuse'){state.view='chat';saveState();render();await sendPrompt(decodeURIComponent(a.dataset.q))}
else if(act==='remove-file'){state.files.splice(+a.dataset.index,1);saveState();files()} else if(act==='analyze-file'){const f=state.files[+a.dataset.index];state.view='chat';saveState();render();await sendPrompt('Analyze my uploaded file named '+f.name+' ('+f.type+'). The browser currently stores its metadata; ask me to paste or attach readable text if needed.')}
else if(act==='save-profile'){const n=$('#setName').value.trim();if(n){user().name=n;save();toast('Profile updated.');render()}}
else if(act==='save-api'){const x=$('#apiUrl').value.trim().replace(/\/$/,'');if(x){localStorage.setItem('zeus_api_url',x);toast('Backend URL saved. Reloading…');setTimeout(()=>location.reload(),400)}}
else if(act==='test-api'){const r=await fetch((localStorage.getItem('zeus_api_url')||API_URL)+'/api/health');const d=await r.json();$('#apiStatus').textContent=`Online • Gemini: ${d.gemini?'ready':'not configured'} • Paystack: ${d.paystack?'ready':'not configured'}`}
else if(act==='export-data'){download('zeus-data.json',JSON.stringify({account:{name:user().name,email:user().email,plan:plan()},state},null,2),'application/json')} else if(act==='reset-data'){if(confirm('Reset all local ZEUS data?')){localStorage.removeItem(KEY);localStorage.removeItem(KEY+'_state');location.reload()}}
else if(act==='redeem')await redeem(); else if(act==='bank-pay'){state.view='upgrade';saveState();render();setTimeout(()=>{const x=$('#paidPlan');if(x)x.value=a.dataset.planName||'PRO';document.querySelector('#paidPlan')?.scrollIntoView({behavior:'smooth',block:'center'});},50)} else if(act==='bank-submit')submitBankPayment(); else if(act==='copy-bank')copyBank(); else if(act==='quick'){state.view='chat';saveState();render();await sendPrompt(a.dataset.q)} else if(act==='library'){toast('Use the prompt library on Home or add your own saved memories.')} 
}catch(err){toast('❌ '+(err.message||'Something went wrong'))}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(b){state.mode=b.dataset.mode;saveState();render()}const p=e.target.closest('[data-plan]');if(p){pay(p.dataset.plan)}});
$('#fileInput').addEventListener('change',e=>addFiles(e.target.files));document.addEventListener('change',e=>{if(e.target.id==='dropInput')addFiles(e.target.files)});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();document.querySelector('[data-action="send"]')?.click()}});$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
loadState();render();
